#!/usr/bin/env perl

##
#  $Id: conmen,v 1.4 2001/06/15 22:56:53 dun Exp $
#    by Chris Dunlap <cdunlap@llnl.gov>
##
#  ConMen is a wrapper to aid in ConMan broadcast sessions.
#  It spawns an xterm for each of the selected consoles
#    and uses the current tty as the broadcast window.
#  All of the spawned xterm clients are terminated when the
#    broadcast window session is closed.
##

use Getopt::Std;


$SIG{'TERM'} = signal_handler;

$ENV{DISPLAY}
    or die("ERROR: DISPLAY is not set.\n");
!system("which conman 1>/dev/null 2>&1")
    or die("ERROR: conman not found in PATH.\n");
!system("which xterm 1>/dev/null 2>&1")
    or die("ERROR: xterm not found in PATH.\n");

$help = `conman -h`;
($def_dst) = ($help =~ /-d .* \(default: ([^\)]*)\)/);
($def_esc) = ($help =~ /-e .* \(default: ([^\)]*)\)/);

if (!@ARGV || !getopts('d:e:fg:hjmV') || $opt_h) {
    print_usage();
}

($opt_f + $opt_j + $opt_m <= 1)
    or die("ERROR: Only one mode [fjr] can be specified.\n");

if ($opt_V) {
    exec("conman -V");
}

$conman = "conman";
$conman .= " -d \'$opt_d\'" if ($opt_d);
$conman .= " -e \'$opt_e\'" if ($opt_e);

if ($opt_f) {
    $mode = "-f";
} elsif ($opt_j) {
    $mode = "-j";
} elsif ($opt_m) {
    $mode = "-m";
} else {
    $mode = "-m";
}

foreach (@ARGV) {
    $_ = "'$_'";
}
$patterns = join(" ", @ARGV);
chomp(@consoles = `$conman -q $patterns`);

if (@consoles == 0) {
    exit(1);
}
if (@consoles == 1) {
    exec("$conman $mode $consoles[0]");
}

$xterm = "xterm";
$xterm .= " -geometry \'$opt_g\'" if ($opt_g);
foreach (@consoles) {
    $name = "\'ConMan: $_\'";
    system("$xterm -T $name -n $name -e $conman $mode $_ &\n");
    select(undef, undef, undef, 0.2);
}
select(undef, undef, undef, 1.0);
system("$conman -bj $patterns");
kill('TERM', -getpid);

exit(0);


sub print_usage
{
    ($prog) = ($0 =~ m|(?:.*/)?([^/]*)|);
    print("Usage: $prog [-d <host>] [-e <char>] [-hfjmV] <console(s)>\n");
    print("\n");
    print("  -h        Display this help.\n");
    print("  -d HOST   Specify location of server (default: $def_dst).\n");
    print("  -e CHAR   Set escape character (default: $def_esc).\n");
    print("  -f        Force connections (console stealing).\n");
    print("  -g SIZE   Specify xterm's geometry (eg, 80x24).\n");
    print("  -j        Join connections (console sharing).\n");
    print("  -m        Monitor connections (read-only).\n");
    print("  -V        Display version information.\n");
    print("\n");
    exit(0);
}


sub signal_handler
{
    exit(0);
}
